[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "cupcakestokilowatts"
authors = [{name = "FormFunctionIO", email = "hi@formfunction.io"}]
dynamic = ["version", "description"]